export const searchAliases: Record<string, string[]> = {
  'творог': ['cottage cheese', 'tvorog', 'curd', 'tvor'],
  'молоко': ['milk', 'dairy', 'molo'],
  'яйцо': ['egg', 'eggs', 'yaytso'],
  'курица': ['chicken', 'poultry', 'kuritsa', 'kura'],
  'говядина': ['beef', 'meat', 'govyadina'],
  'рис': ['rice', 'grain', 'ris'],
  'овсянка': ['oats', 'oatmeal', 'porridge', 'ovsyanka'],
  'рыба': ['fish', 'seafood', 'ryba'],
  'мясо': ['meat', 'beef', 'chicken', 'pork', 'myaso'],
  'яблоко': ['apple', 'fruit', 'yabloko'],
  'банан': ['banana', 'fruit', 'banan'],
  'орехи': ['nuts', 'almonds', 'walnuts', 'orekhi'],
  'йогурт': ['yogurt', 'dairy', 'yogurt', 'epica', 'teos'],
  'сыр': ['cheese', 'dairy', 'syr', 'parmesan'],
  'хлеб': ['bread', 'grain', 'khleb'],
  'макароны': ['pasta', 'grain', 'macaroni'],
  'гречка': ['buckwheat', 'grain', 'grechka'],
  'творожный': ['cottage cheese'],
  'chicken': ['курица', 'chick'],
  'beef': ['говядина'],
  'rice': ['рис'],
  'milk': ['молоко'],
  'egg': ['яйцо'],
  'fish': ['рыба'],
  'meat': ['мясо'],
  'fruit': ['фрукты', 'яблоко', 'банан'],
  'vegetables': ['овощи', 'veggies'],
  'nuts': ['орехи'],
  'bread': ['хлеб'],
  'pasta': ['макароны'],
  'porridge': ['каша', 'овсянка'],
  'buckwheat': ['гречка'],
  'potato': ['картофель', 'картошка', 'potat'],
  'tomato': ['помидор', 'томат'],
  'yogurt': ['йогурт', 'йогурт', 'epica', 'teos'],
  'epica': ['йогурт', 'yogurt'],
  'teos': ['йогурт', 'yogurt'],
  'danone': ['йогурт', 'молоко'],
};

export const categoryAliases: Record<string, string> = {
  'мясо': 'meat',
  'птица': 'meat',
  'рыба': 'fish',
  'морепродукты': 'fish',
  'молочка': 'dairy',
  'молочные': 'dairy',
  'крупы': 'grain',
  'каши': 'grain',
  'овощи': 'veggies',
  'фрукты': 'fruit',
  'ягоды': 'fruit',
  'орехи': 'fats',
  'масла': 'fats',
  'снеки': 'snacks',
  'перекусы': 'snacks',
  'горячее': 'meals',
  'блюда': 'meals',
  'meat': 'meat',
  'fish': 'fish',
  'dairy': 'dairy',
  'grain': 'grain',
  'veggies': 'veggies',
  'fruit': 'fruit',
  'fats': 'fats',
  'snacks': 'snacks',
  'meals': 'meals',
};
