export const englishToRussian: Record<string, string> = {
  'apple': 'яблоко',
  'banana': 'банан',
  'milk': 'молоко',
  'chicken': 'курица',
  'beef': 'говядина',
  'rice': 'рис',
  'potato': 'картофель',
  'bread': 'хлеб',
  'egg': 'яйцо',
  'yogurt': 'йогурт',
  'cheese': 'сыр',
  'water': 'вода',
  'coffee': 'кофе',
  'tea': 'чай',
  'juice': 'сок',
  'pasta': 'макароны',
  'pork': 'свинина',
  'turkey': 'индейка',
  'fish': 'рыба',
  'salmon': 'лосось',
  'tuna': 'тунец',
  'shrimp': 'креветки',
  'tomato': 'помидор',
  'cucumber': 'огурец',
  'onion': 'лук',
  'garlic': 'чеснок',
  'carrot': 'морковь',
  'cabbage': 'капуста',
  'broccoli': 'брокколи',
  'spinach': 'шпинат',
  'strawberry': 'клубника',
  'orange': 'апельсин',
  'lemon': 'лимон',
  'grape': 'виноград',
  'watermelon': 'арбуз',
  'oats': 'овес',
  'buckwheat': 'гречка',
  'honey': 'мед',
  'sugar': 'сахар',
  'salt': 'соль',
  'oil': 'масло',
  'butter': 'сливочное масло',
  'nuts': 'орехи',
  'almond': 'миндаль',
  'walnut': 'грецкий орех',
  'protein': 'белок',
  'shake': 'коктейль',
  'bar': 'батончик',
  'chocolate': 'шоколад'
};

export const categoriesRu: Record<string, string> = {
  'meat': 'Мясо',
  'fish': 'Рыба',
  'dairy': 'Молочные продукты',
  'grain': 'Крупы и злаки',
  'veggies': 'Овощи',
  'fruit': 'Фрукты',
  'fats': 'Жиры и масла',
  'snacks': 'Снеки',
  'beverages': 'Напитки'
};
